### ISSUE TITLE
OSX / nw_demo / ./nw_cocoa.lua:1242: 'struct CGRect' is not callable

### ISSUE THREAD

**Issue by Robert-M-Muench** [luapower/nw#67]
mac-pro:luapower robby$ ./luajit nw_demo.lua
/Volumes/Daten/windows/d/develop/Lua/luapower/bin/osx64/luajit-bin: ./nw_cocoa.lua:1242: 'struct CGRect' is not callable
stack traceback:
    [C]: in function 'frame'
    ./nw_cocoa.lua:1242: in function 'main_display'
    nw_demo.lua:8: in main chunk
    [C]: at 0x0100000b90

**Comment by curioussavage** [comment]
I tried to run the nw example from the docs with the zip from the website and I still get this.

```
/Users/awinn/dev/luapower/bin/osx64/luajit-bin: /Users/awinn/dev/luapower/bin/osx64/../../nw_cocoa.lua:34: 'struct CGRect' is not callable
stack traceback:
	[C]: in function 'frame'
	/Users/awinn/dev/luapower/bin/osx64/../../nw_cocoa.lua:34: in function 'primary_screen_h'
	/Users/awinn/dev/luapower/bin/osx64/../../nw_cocoa.lua:39: in function 'flip_screen_rect'
	/Users/awinn/dev/luapower/bin/osx64/../../nw_cocoa.lua:180: in function 'new'
	/Users/awinn/dev/luapower/bin/osx64/../../nw.lua:527: in function 'window'
	test.lua:5: in main chunk
	[C]: at 0x0100000b90
```

**Comment by capr** [comment]
fixed in objc
